required: sudo

language: elixir

elixir: '1.6.6'

addons:
  postgresql: '9.6'

services:
  - postgresql

before_install:
  - cd src

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

env:
  - MIX_ENV=test mix phx.server

script:
  - mix test
