---
version: '3'
services:
  app:
    image: phoenix:1.3.4
    build: .
    ports:
      - "4000:4000"
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: yelp_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
